version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "musical_ocean_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "PostgresFreak10#"
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
